// src/app/sections/certifications/certifications.component.ts
import { Component } from '@angular/core';
import { CERTIFICATIONS } from '../../data/certifications';

@Component({
  selector: 'app-certifications',
  template: `
    <app-section id="certifications" heading="Certifications">
      <ul class="space-y-2">
        <li *ngFor="let cert of certifications" class="dark:text-white">
          <span class="font-semibold">{{ cert.name }}</span>
          <span *ngIf="cert.issuer"> | {{ cert.issuer }}</span>
          <span *ngIf="cert.date" class="text-sm text-gray-500 dark:text-gray-400"> ({{ cert.date }})</span>
        </li>
      </ul>
    </app-section>
  `,
})
export class CertificationsComponent {
  readonly certifications = CERTIFICATIONS;
}

// src/components/sections/certifications.tsx
import Section from "@/components/ui/section";
import { CERTIFICATIONS } from "@/data/certifications";

export default function Certifications() {
  return (
    <Section id="certifications" heading="Certifications">
      <ul className="space-y-2">
        {CERTIFICATIONS.map((cert) => (
          <li key={cert.name} className="dark:text-white">
            <span className="font-semibold">{cert.name}</span>
            {cert.issuer && <span> | {cert.issuer}</span>}
            {cert.date && <span className="text-sm text-gray-500 dark:text-gray-400"> ({cert.date})</span>}
          </li>
        ))}
      </ul>
    </Section>
  );
}
