// src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { initFlowbite } from 'flowbite';

@Component({
  selector: 'app-root',
  template: `
    <app-navbar></app-navbar>
    <div class="m-5 pl-5">
      <app-intro></app-intro>
      <app-about></app-about>
      <app-projects></app-projects>
      <app-certifications></app-certifications>
      <app-contact></app-contact>
      <app-footer></app-footer>
    </div>
  `,
})
export class AppComponent implements OnInit {
  title = 'portfolio';

  ngOnInit(): void {
    initFlowbite();
  }
}

// src/app/page.tsx
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";
import About from "@/components/sections/about/about";
import Certifications from "@/components/sections/certifications";
import Contact from "@/components/sections/contact";
import Intro from "@/components/sections/intro";
import Projects from "@/components/sections/projects/projects";

export default function Home() {
  return (
    <>
      <Navbar />
      <main className="m-5 pl-5">
        <Intro />
        <About />
        <Projects />
        <Certifications />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
