// src/components/sections/about/about.tsx
import Section from "@/components/ui/section";
import { EXPERIENCE } from "@/data/experience";
import TimelineItem from "./timeline-item";

export default function About() {
  return (
    <Section id="about" heading="About Me">
      <ol className="items-center sm:flex">
        {EXPERIENCE.map((entry) => (
          <TimelineItem key={entry.title} entry={entry} />
        ))}
      </ol>
    </Section>
  );
}

// src/app/sections/about/about.component.ts
import { Component } from '@angular/core';
import { EXPERIENCE } from '../../data/experience';

@Component({
  selector: 'app-about',
  template: `
    <app-section id="about" heading="About Me">
      <ol class="items-center sm:flex">
        <app-timeline-item
          *ngFor="let entry of experience"
          [entry]="entry"
        ></app-timeline-item>
      </ol>
    </app-section>
  `,
})
export class AboutComponent {
  readonly experience = EXPERIENCE;
}
