// src/app/sections/about/timeline-item/timeline-item.component.ts
import { Component, Input } from '@angular/core';
import { TimelineEntry } from '../../../models/timeline-entry';

@Component({
  selector: 'app-timeline-item',
  template: `
   <li class="relative mb-6 sm:mb-0">
        <div class="flex items-center">
            <div class="z-10 flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full ring-0 ring-white dark:bg-blue-900 sm:ring-8 dark:ring-gray-900 shrink-0">
                <svg class="w-2.5 h-2.5 text-blue-800 dark:text-blue-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                </svg>
            </div>
            <div class="hidden sm:flex w-full bg-gray-200 h-0.5 dark:bg-gray-700"></div>
        </div>
        <div class="mt-3 sm:pe-8">
            <h3 class="text-lg font-semibold text-gray-900 dark:text-white">{{ entry.title }}</h3>
            <time *ngIf="entry.date" class="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">{{ entry.date }}</time>
            <p *ngIf="entry.description" class="text-base font-normal text-gray-500 dark:text-gray-400">{{ entry.description }}</p>
        </div>
    </li>
  `,
})
export class TimelineItemComponent {
  @Input({ required: true }) entry!: TimelineEntry;
}

// src/components/sections/about/timeline-item.tsx
import type { TimelineEntry } from "@/types/timeline-entry";

export default function TimelineItem({ entry }: { entry: TimelineEntry }) {
  return (
    <li className="relative mb-6 sm:mb-0">
      <div className="flex items-center">
        <div className="z-10 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-100 ring-0 ring-white sm:ring-8 dark:bg-blue-900 dark:ring-gray-900">
          <svg className="h-2.5 w-2.5 text-blue-800 dark:text-blue-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z" />
          </svg>
        </div>
        <div className="hidden h-0.5 w-full bg-gray-200 sm:flex dark:bg-gray-700" />
      </div>
      <div className="mt-3 sm:pe-8">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white">{entry.title}</h3>
        {entry.date && (
          <time className="mb-2 block text-sm leading-none font-normal text-gray-400 dark:text-gray-500">{entry.date}</time>
        )}
        {entry.description && (
          <p className="text-base font-normal text-gray-500 dark:text-gray-400">{entry.description}</p>
        )}
      </div>
    </li>
  );
}
