// src/app/sections/projects/projects.component.ts
import { Component } from '@angular/core';
import { PROJECTS } from '../../data/projects';

@Component({
  selector: 'app-projects',
  template: `
    <app-section id="projects" heading="Projects">
      <div class="lg:grid lg:grid-cols-4 lg:gap-2 grid border">
        <app-image-container
          *ngFor="let project of projects"
          [src]="project.imageUrl"
        ></app-image-container>
      </div>
    </app-section>
  `,
})
export class ProjectsComponent {
  readonly projects = PROJECTS;
}

// src/components/sections/projects/projects.tsx
import Section from "@/components/ui/section";
import { PROJECTS } from "@/data/projects";
import ImageContainer from "./image-container";

export default function Projects() {
  return (
    <Section id="projects" heading="Projects">
      <div className="grid border lg:grid lg:grid-cols-4 lg:gap-2">
        {PROJECTS.map((project, i) => (
          <ImageContainer key={i} src={project.imageUrl} />
        ))}
      </div>
    </Section>
  );
}
